name: Unit Testting

on:
  pull_request:
    branches: [main]
  push:
    branches: [feature/**, devel/**]

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: cd back && yarn install

      - name: Start Testing
        run: cd back && yarn test

  test-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: cd front && yarn install

      - name: Start Testing
        run: cd front && yarn test
