name: Unit Testting

on:
  pull_request:
    branches: [main]
  push:
    branches: [feature/**, devel/**]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Modules
        run: cd back && yarn install

      - name: Check lint on entire project
        run: cd back && yarn lint

      - name: Start Testing
        run: cd back && yarn test
